// node test/legal-pages.mjs            check site/privacy.html, terms.html and support.html are current
// node test/legal-pages.mjs --write    write them
//
// The app stores need the privacy policy, the terms and a support page at real addresses
// (hitquota.app/privacy, /terms, /support). The words already live in the app, in LEGAL,
// where people agree to them. These pages are built from that same text so the website can
// never say something different from what somebody agreed to in the app.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(ROOT, 'app', 'index.html'), 'utf8');
const pick = re => (html.match(re) || [])[1];
const CONTACT = pick(/const CONTACT = '([^']+)'/), SITE = pick(/const SITE = '([^']+)'/);
const VERSION = pick(/const TERMS_VERSION = '([^']+)'/);
const src = html.slice(html.indexOf('// legal:start'), html.indexOf('// legal:end'));
if (!CONTACT || !SITE || !VERSION || !src) throw new Error('legal-pages: could not find LEGAL, CONTACT, SITE or TERMS_VERSION in app/index.html');
const LEGAL = new Function('CONTACT', 'SITE', `${src}; return LEGAL;`)(CONTACT, SITE);

const page = (title, lead, body) => `<!doctype html>
<!-- GENERATED by test/legal-pages.mjs from app/index.html. Edit the words there, then run it with --write. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>${title} · Quota</title>
<meta name="description" content="${lead}">
<meta name="theme-color" content="#ffffff">
<link rel="icon" href="/icon-192.png">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&display=swap">
<style>
:root{--ink:#1d1d1f;--mute:#6e6e73;--line:#d2d2d7;--g1:#12934f;color-scheme:light}
*{box-sizing:border-box}
body{margin:0;background:#fff;color:var(--ink);font:17px/1.55 Geist,-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;-webkit-font-smoothing:antialiased;letter-spacing:-.011em}
a{color:var(--g1);text-decoration:none}a:hover{text-decoration:underline}
nav{border-bottom:1px solid var(--line);padding:max(14px,env(safe-area-inset-top)) 16px 14px}
nav div,main,footer div{max-width:720px;margin:0 auto}
nav a{color:var(--ink);font-weight:600;font-size:19px}
main{padding:40px 16px 64px}
h1{font-size:40px;line-height:1.1;letter-spacing:-.03em;margin:0 0 8px;font-weight:600}
h2{font-size:26px;letter-spacing:-.02em;margin:48px 0 8px;font-weight:600}
h3{font-size:19px;margin:28px 0 6px;font-weight:600}
.lead{color:var(--mute);font-size:19px;margin:0}
.stamp{color:var(--mute);font-size:14px;margin-top:6px}
ul{padding-left:22px}li{margin:6px 0}
details{border-bottom:1px solid var(--line);padding:14px 0}summary{cursor:pointer;font-weight:600}
footer{border-top:1px solid var(--line);padding:24px 16px calc(24px + env(safe-area-inset-bottom));color:var(--mute);font-size:14px}
footer a{margin-right:18px}
</style>
</head>
<body>
<nav><div><a href="/">Quota</a></div></nav>
<main>
<h1>${title}</h1>
<p class="lead">${lead}</p>
${body}
</main>
<footer><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/support">Support</a><a href="mailto:${CONTACT}">${CONTACT}</a></div></footer>
</body>
</html>
`;
const doc = (d, first) => `${first ? '' : `<h2>${d.title}</h2>`}${d.body}`;
const stamp = `<p class="stamp">Last updated ${VERSION}</p>`;

const PAGES = {
  'privacy.html': page('Privacy policy', 'What Quota keeps, why, and who can see it.',
    `${stamp}\n${doc(LEGAL.privacy, true)}\n${doc(LEGAL.cookies)}`),
  'terms.html': page('Terms of use', 'The agreement between you and Quota, and the community guidelines that are part of it.',
    `${stamp}\n${doc(LEGAL.terms, true)}\n${doc(LEGAL.guidelines)}`),
  'support.html': page('Support', 'Questions, problems, reports and your data. One address for all of it.', `
<h2>Contact</h2>
<p>Email <a href="mailto:${CONTACT}">${CONTACT}</a>. One of the two people who make Quota answers, usually within a day. For a problem, say your username, your phone, and what you were doing; a screenshot helps most.</p>
<h2>Reporting something</h2>
<p>In the app, tap ⋯ on a post or a story, or press and hold a comment or a message, and choose Report. Report is also on everybody's profile. Every report is looked at within 24 hours, and anything that breaks the <a href="/terms">terms and community guidelines</a> is taken down. You can also email <a href="mailto:${CONTACT}">${CONTACT}</a>.</p>
<h2>Blocking somebody</h2>
<p>On their profile, or from the ⋯ on anything they posted, choose Block. Everything they make disappears for you straight away, you stop being friends, and they are not told. Settings → Blocked people undoes it.</p>
<h2>Deleting your account</h2>
<p>In the app: Settings → Delete my account, then type <b>delete</b>. Your account and everything in it (posts, clips, stories, comments, messages, friends) are deleted straight away. If you can't get into the app, email <a href="mailto:${CONTACT}">${CONTACT}</a> from the address on the account and it will be done within 30 days.</p>
<h2>Questions</h2>
<details><summary>What counts as proof?</summary><p>A photo or a clip, taken with Quota's camera that day. Something old from your camera roll won't go through.</p></details>
<details><summary>Who can see my posts?</summary><p>The members of the group you posted in, and nobody else. There is no public feed.</p></details>
<details><summary>I forgot my password.</summary><p>Tap "Forgotten it?" on the log in screen. We email you a code, and you choose a new password with it.</p></details>
<details><summary>My clip is stuck uploading.</summary><p>If you lost your connection it is saved on your phone and goes up on its own when you're back. If it stays stuck, email us.</p></details>
<details><summary>I'm not getting notifications.</summary><p>Check Settings → Notifications in Quota, then your phone's Settings → Quota → Notifications.</p></details>
<details><summary>Does Quota cost anything or show ads?</summary><p>It is free, with no ads, no trackers and no cookies.</p></details>
<details><summary>Can I get a copy of my data?</summary><p>Yes. Email <a href="mailto:${CONTACT}">${CONTACT}</a> and you'll have it within 30 days.</p></details>`),
};

const write = process.argv.includes('--write');
let stale = [];
for (const [f, out] of Object.entries(PAGES)) {
  const at = join(ROOT, 'site', f);
  if (write) { writeFileSync(at, out); console.log(`wrote site/${f}`); continue; }
  let now = ''; try { now = readFileSync(at, 'utf8'); } catch {}
  if (now !== out) stale.push(f);
}
if (stale.length) {
  console.log(`FAIL: site/${stale.join(', site/')} out of date with LEGAL in app/index.html. Run: node test/legal-pages.mjs --write`);
  process.exit(1);
}
if (!write) console.log('PASS: the website says what the app says');
